server {
  listen       80;
  server_name  _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:ico|css|js|json|png|jpg|jpeg|gif|svg|map)$ {
    expires 1y;
    add_header Cache-Control "public";
    try_files $uri =404;
  }
}
